### ISSUE TITLE
Replace GConf names with MceSettings

### ISSUE THREAD

**Issue by thp** [nemomobile/mce#240]
Coming from https://github.com/nemomobile/mce/issues/239:

Now that mce doesn't use GConf anymore, the names in the sources could be confusing. Rework it so that all filenames/constants/macros/definitions/functions are called something like `mce_settings_` instead of gconf. So:

 * `mce_gconf_`... becomes `mce_settings_`...
 * `GCONF_`... becomes `MCE_SETTING_`...
 * `GConf`... becomes `MceSettings`...

(and anything that I forgot)

Simo says:

Yes, all of it is contained within mce. The only problem is that fixing needs global search+replace - which mean it would make rebasing work in progress stuff gets ugly -> preferrable to do it at time where no major features are in the air.

**Comment by spiiroin** [comment]
When there is a fix, it needs a bug ref to get past integration bots -> issue duplicated at nemo bugzilla:
https://bugs.nemomobile.org/show_bug.cgi?id=799

**Comment by spiiroin** [comment]
Mer bugzilla is used nowadays for mce, not nemo bz, bug at:
https://bugs.merproject.org/show_bug.cgi?id=1554
